/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiClaimFreeRouteImport } from './routes/api/claim-free'
import { Route as ApiDispatchRouteImport } from './routes/api/dispatch'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin.deposits'
import { Route as AuthenticatedAdminGuildRouteImport } from './routes/_authenticated/admin.guild'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminPanelsRouteImport } from './routes/_authenticated/admin.panels'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSliderRouteImport } from './routes/_authenticated/admin.slider'
import { Route as AuthenticatedAdminVisitOrdersRouteImport } from './routes/_authenticated/admin.visit-orders'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCouponsRouteImport } from './routes/_authenticated/dashboard.coupons'
import { Route as AuthenticatedDashboardDepositRouteImport } from './routes/_authenticated/dashboard.deposit'
import { Route as AuthenticatedDashboardDepositResultRouteImport } from './routes/_authenticated/dashboard.deposit-result'
import { Route as AuthenticatedDashboardGuildRouteImport } from './routes/_authenticated/dashboard.guild'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardPackagesRouteImport } from './routes/_authenticated/dashboard.packages'
import { Route as AuthenticatedDashboardPanelsRouteImport } from './routes/_authenticated/dashboard.panels'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard.wallet'
import { Route as ApiPublicBohudurWebhookRouteImport } from './routes/api/public/bohudur-webhook'
import { Route as ApiPublicCronLikesRouteImport } from './routes/api/public/cron-likes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiClaimFreeRoute = ApiClaimFreeRouteImport.update({
  id: '/api/claim-free',
  path: '/api/claim-free',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDispatchRoute = ApiDispatchRouteImport.update({
  id: '/api/dispatch',
  path: '/api/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuildRoute = AuthenticatedAdminGuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPanelsRoute =
  AuthenticatedAdminPanelsRouteImport.update({
    id: '/panels',
    path: '/panels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSliderRoute =
  AuthenticatedAdminSliderRouteImport.update({
    id: '/slider',
    path: '/slider',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVisitOrdersRoute =
  AuthenticatedAdminVisitOrdersRouteImport.update({
    id: '/visit-orders',
    path: '/visit-orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCouponsRoute =
  AuthenticatedDashboardCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDepositRoute =
  AuthenticatedDashboardDepositRouteImport.update({
    id: '/deposit',
    path: '/deposit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDepositResultRoute =
  AuthenticatedDashboardDepositResultRouteImport.update({
    id: '/deposit-result',
    path: '/deposit-result',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuildRoute =
  AuthenticatedDashboardGuildRouteImport.update({
    id: '/guild',
    path: '/guild',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPackagesRoute =
  AuthenticatedDashboardPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPanelsRoute =
  AuthenticatedDashboardPanelsRouteImport.update({
    id: '/panels',
    path: '/panels',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicBohudurWebhookRoute = ApiPublicBohudurWebhookRouteImport.update({
  id: '/api/public/bohudur-webhook',
  path: '/api/public/bohudur-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronLikesRoute = ApiPublicCronLikesRouteImport.update({
  id: '/api/public/cron-likes',
  path: '/api/public/cron-likes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/claim-free': typeof ApiClaimFreeRoute
  '/api/dispatch': typeof ApiDispatchRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/guild': typeof AuthenticatedAdminGuildRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/panels': typeof AuthenticatedAdminPanelsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/slider': typeof AuthenticatedAdminSliderRoute
  '/admin/visit-orders': typeof AuthenticatedAdminVisitOrdersRoute
  '/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/dashboard/deposit': typeof AuthenticatedDashboardDepositRoute
  '/dashboard/deposit-result': typeof AuthenticatedDashboardDepositResultRoute
  '/dashboard/guild': typeof AuthenticatedDashboardGuildRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/bohudur-webhook': typeof ApiPublicBohudurWebhookRoute
  '/api/public/cron-likes': typeof ApiPublicCronLikesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/claim-free': typeof ApiClaimFreeRoute
  '/api/dispatch': typeof ApiDispatchRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/guild': typeof AuthenticatedAdminGuildRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/panels': typeof AuthenticatedAdminPanelsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/slider': typeof AuthenticatedAdminSliderRoute
  '/admin/visit-orders': typeof AuthenticatedAdminVisitOrdersRoute
  '/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/dashboard/deposit': typeof AuthenticatedDashboardDepositRoute
  '/dashboard/deposit-result': typeof AuthenticatedDashboardDepositResultRoute
  '/dashboard/guild': typeof AuthenticatedDashboardGuildRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/bohudur-webhook': typeof ApiPublicBohudurWebhookRoute
  '/api/public/cron-likes': typeof ApiPublicCronLikesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/claim-free': typeof ApiClaimFreeRoute
  '/api/dispatch': typeof ApiDispatchRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin/guild': typeof AuthenticatedAdminGuildRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/panels': typeof AuthenticatedAdminPanelsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/slider': typeof AuthenticatedAdminSliderRoute
  '/_authenticated/admin/visit-orders': typeof AuthenticatedAdminVisitOrdersRoute
  '/_authenticated/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/_authenticated/dashboard/deposit': typeof AuthenticatedDashboardDepositRoute
  '/_authenticated/dashboard/deposit-result': typeof AuthenticatedDashboardDepositResultRoute
  '/_authenticated/dashboard/guild': typeof AuthenticatedDashboardGuildRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/_authenticated/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/bohudur-webhook': typeof ApiPublicBohudurWebhookRoute
  '/api/public/cron-likes': typeof ApiPublicCronLikesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/api/claim-free'
    | '/api/dispatch'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/deposits'
    | '/admin/guild'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/panels'
    | '/admin/settings'
    | '/admin/slider'
    | '/admin/visit-orders'
    | '/dashboard/coupons'
    | '/dashboard/deposit'
    | '/dashboard/deposit-result'
    | '/dashboard/guild'
    | '/dashboard/orders'
    | '/dashboard/packages'
    | '/dashboard/panels'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/api/public/bohudur-webhook'
    | '/api/public/cron-likes'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/claim-free'
    | '/api/dispatch'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/deposits'
    | '/admin/guild'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/panels'
    | '/admin/settings'
    | '/admin/slider'
    | '/admin/visit-orders'
    | '/dashboard/coupons'
    | '/dashboard/deposit'
    | '/dashboard/deposit-result'
    | '/dashboard/guild'
    | '/dashboard/orders'
    | '/dashboard/packages'
    | '/dashboard/panels'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/api/public/bohudur-webhook'
    | '/api/public/cron-likes'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/claim-free'
    | '/api/dispatch'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/deposits'
    | '/_authenticated/admin/guild'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/panels'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/slider'
    | '/_authenticated/admin/visit-orders'
    | '/_authenticated/dashboard/coupons'
    | '/_authenticated/dashboard/deposit'
    | '/_authenticated/dashboard/deposit-result'
    | '/_authenticated/dashboard/guild'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/packages'
    | '/_authenticated/dashboard/panels'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/wallet'
    | '/api/public/bohudur-webhook'
    | '/api/public/cron-likes'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiClaimFreeRoute: typeof ApiClaimFreeRoute
  ApiDispatchRoute: typeof ApiDispatchRoute
  ApiPublicBohudurWebhookRoute: typeof ApiPublicBohudurWebhookRoute
  ApiPublicCronLikesRoute: typeof ApiPublicCronLikesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/claim-free': {
      id: '/api/claim-free'
      path: '/api/claim-free'
      fullPath: '/api/claim-free'
      preLoaderRoute: typeof ApiClaimFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispatch': {
      id: '/api/dispatch'
      path: '/api/dispatch'
      fullPath: '/api/dispatch'
      preLoaderRoute: typeof ApiDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deposits': {
      id: '/_authenticated/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guild': {
      id: '/_authenticated/admin/guild'
      path: '/guild'
      fullPath: '/admin/guild'
      preLoaderRoute: typeof AuthenticatedAdminGuildRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/panels': {
      id: '/_authenticated/admin/panels'
      path: '/panels'
      fullPath: '/admin/panels'
      preLoaderRoute: typeof AuthenticatedAdminPanelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slider': {
      id: '/_authenticated/admin/slider'
      path: '/slider'
      fullPath: '/admin/slider'
      preLoaderRoute: typeof AuthenticatedAdminSliderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/visit-orders': {
      id: '/_authenticated/admin/visit-orders'
      path: '/visit-orders'
      fullPath: '/admin/visit-orders'
      preLoaderRoute: typeof AuthenticatedAdminVisitOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/coupons': {
      id: '/_authenticated/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof AuthenticatedDashboardCouponsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/deposit': {
      id: '/_authenticated/dashboard/deposit'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof AuthenticatedDashboardDepositRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/deposit-result': {
      id: '/_authenticated/dashboard/deposit-result'
      path: '/deposit-result'
      fullPath: '/dashboard/deposit-result'
      preLoaderRoute: typeof AuthenticatedDashboardDepositResultRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guild': {
      id: '/_authenticated/dashboard/guild'
      path: '/guild'
      fullPath: '/dashboard/guild'
      preLoaderRoute: typeof AuthenticatedDashboardGuildRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/packages': {
      id: '/_authenticated/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof AuthenticatedDashboardPackagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/panels': {
      id: '/_authenticated/dashboard/panels'
      path: '/panels'
      fullPath: '/dashboard/panels'
      preLoaderRoute: typeof AuthenticatedDashboardPanelsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/bohudur-webhook': {
      id: '/api/public/bohudur-webhook'
      path: '/api/public/bohudur-webhook'
      fullPath: '/api/public/bohudur-webhook'
      preLoaderRoute: typeof ApiPublicBohudurWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-likes': {
      id: '/api/public/cron-likes'
      path: '/api/public/cron-likes'
      fullPath: '/api/public/cron-likes'
      preLoaderRoute: typeof ApiPublicCronLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminGuildRoute: typeof AuthenticatedAdminGuildRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPanelsRoute: typeof AuthenticatedAdminPanelsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSliderRoute: typeof AuthenticatedAdminSliderRoute
  AuthenticatedAdminVisitOrdersRoute: typeof AuthenticatedAdminVisitOrdersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
  AuthenticatedAdminGuildRoute: AuthenticatedAdminGuildRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
  AuthenticatedAdminPanelsRoute: AuthenticatedAdminPanelsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSliderRoute: AuthenticatedAdminSliderRoute,
  AuthenticatedAdminVisitOrdersRoute: AuthenticatedAdminVisitOrdersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCouponsRoute: typeof AuthenticatedDashboardCouponsRoute
  AuthenticatedDashboardDepositRoute: typeof AuthenticatedDashboardDepositRoute
  AuthenticatedDashboardDepositResultRoute: typeof AuthenticatedDashboardDepositResultRoute
  AuthenticatedDashboardGuildRoute: typeof AuthenticatedDashboardGuildRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPackagesRoute: typeof AuthenticatedDashboardPackagesRoute
  AuthenticatedDashboardPanelsRoute: typeof AuthenticatedDashboardPanelsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCouponsRoute: AuthenticatedDashboardCouponsRoute,
    AuthenticatedDashboardDepositRoute: AuthenticatedDashboardDepositRoute,
    AuthenticatedDashboardDepositResultRoute:
      AuthenticatedDashboardDepositResultRoute,
    AuthenticatedDashboardGuildRoute: AuthenticatedDashboardGuildRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPackagesRoute: AuthenticatedDashboardPackagesRoute,
    AuthenticatedDashboardPanelsRoute: AuthenticatedDashboardPanelsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiClaimFreeRoute: ApiClaimFreeRoute,
  ApiDispatchRoute: ApiDispatchRoute,
  ApiPublicBohudurWebhookRoute: ApiPublicBohudurWebhookRoute,
  ApiPublicCronLikesRoute: ApiPublicCronLikesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
